services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node_modules:/home/vscode/app/node_modules
      - ../:/home/vscode/app:cached
    networks:
      - default
    tty: true
    stdin_open: true

volumes:
  node_modules:


networks:
  thunder:
    external: true
